### ISSUE TITLE
Docker last_downloaded is always 1970-01-01T01:00:00+01:00

### ISSUE THREAD

**Issue by simonstamm** [crazy-max/artifactory-cleanup#150]
### Behaviour

The setting `lastDownloaded: true` is not taken into account because the last_downloaded for docker images is always `1970-01-01T01:00:00+01:00`.

### Configuration

* Artifactory Cleanup version (0.1.0): 1.5.0
* Platform (windows/linux/freebsd/macos): Tested on MacOS and Linux
* JFrog Artifactory version: 7.35.2

### Logs

```
Wed, 27 Apr 2022 11:30:20 CEST TRC Artifactory docker tag last modified response last_modified={"lastModified":"2022-04-23T00:22:07.230+0000","uri":"https://example/artifactory/api/storage/local-docker/foo/bar/manifest.json"}
Wed, 27 Apr 2022 11:30:20 CEST TRC Artifactory artifact file stats response file_stats={"downloadCount":0,"lastDownloaded":0,"remoteDownloadCount":0,"remoteLastDownloaded":0,"uri":"https://example/artifactory/local-docker/foo/bar"}
Wed, 27 Apr 2022 11:30:20 CEST INF Image will be removed docker_repo=foo/bar dry_run=true last_downloaded=1970-01-01T01:00:00+01:00 last_modified=2022-04-23T00:22:07Z policy=policy_docker registry=local-docker size=892MB tag=bar
```

### Solution

My suggested solution is to add `/manifest.json` also to the last downloaded call in https://github.com/crazy-max/artifactory-cleanup/blob/b5721f2c296cb4b07d8cf3636893d9ccf9402b71/pkg/artifactory/docker.go#L98 like:

```go
 return c.LastDownloaded(registry, path.Join(repo, tag, "manifest.json")) 
```

Or is there any reason you added not the `manifest.json`? I can reproduce it via the Artifactory API. When calling the file stats call to the docker folder it's returning "lastDownloaded: 0", when querying the `manifest.json` it has a proper value set.

**Comment by simonstamm** [comment]
Hey @crazy-max, are you interested in changing this? If not, I'll simply fork it. :-)

**Comment by crazy-max** [comment]
@simonstamm I don't recall having this issue with Artifactory 7.18.6 but maybe it has changed after that. LGTM to rely on `manifest.json`.
